import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const mediaLinks = [{
      'name': 'LinkedIn',
      'endpoint': 'https://www.linkedin.com/in/thisisadityapatel/',
      'icon': 'bi-linkedin',
    },
    {
      'name': 'GitHub',
      'endpoint': 'https://github.com/thisisadityapatel',
      'icon': 'bi-github',
    },
    {
      'name': 'Resume',
      'endpoint': '/Resume_Aditya_Patel.pdf',
      'icon': 'bi-filetype-pdf',
    },
    {
      'name': 'Email',
      'endpoint': 'mailto:adityakdpatel@gmail.com',
      'icon': 'bi-envelope-fill',
    },
    {
      'name': 'Calender',
      'endpoint': 'https://calendly.com/adityakdpatel/30min',
      'icon': 'bi-calendar-week'
    }
  ]

  const current_Date = new Date();

  return (
    <>
      <Head>
        <title>Aditya Patel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container introDiv portfolioElement">
        <div className="text-center my-5">
            <img src="/introImage-compressed.jpg" alt={"Aditya Patel Profile Picture"} className="introProfileImage border border-5 rounded-circle"/>
        </div>
        <p> 
            {"Hey, I'm"} <span style={{textDecoration: "none"}}>{"Aditya Patel"}</span> {", I'm a "} <span style={{textDecoration: "underline"}}>{"Computer Science"}</span> {" undergrad at"} <Link href="https://www.torontomu.ca/about/" target='_blank' className="introLink hover-underline-animation">Toronto Metropolitan University</Link> {"in my senior year, planning to graduate by 2026. A passionate programmer, I like challenging myself to do things I’ve never accomplished before and I strive to learn, build and engineer stuff (checkout my "} <Link className="introLink hover-underline-animation" href="./misc">{"Projects"}</Link>{")."}
        </p>
        <p>
            {"Currently a "} <span style={{textDecoration: "underline"}}>{"Software Engineering Intern"}</span> {" at "} 
            <Link href="/experience/RBC" className="introLink hover-underline-animation">Royal Bank of Canada</Link> 
            {" for the Helios Gen-AI and Insights Engineering team. I'm an incoming "}<span style={{textDecoration: "underline"}}>{"Software Engineering Intern"}</span>{" at "} <Link href="/experience/Wealthsimple" className="introLink hover-underline-animation">Wealthsimple</Link> {" and also previously interned as a "}<span style={{textDecoration: "underline"}}>{"Trade Floor Software Developer Intern"}</span> {"for"} <Link href="/experience/Scotiabank" className="introLink hover-underline-animation">Scotiabank GBM</Link> {" and am open to Internship/Research opportunities."}
        </p>
        <p>
            {"I'm into Swimming and Basketball, I also love talking about F1, Physics and about different food options here in Toronto - So feel free to shoot me an email - "} <span><a className="hover-underline-animation introLink" href="mailto:adityakdpatel@gmail.com">adityakdpatel@gmail.com</a></span> {" , or set-up some time in my schedule by clicking the calendar below!"}
        </p>
        <div className="introSocials">
          {
            mediaLinks.map((item, index) => {
              return <Link href={item.endpoint} className="introSocialIconLink" target="_blank" key={index}><i className={"bi " + item.icon + " introIconFont"}></i></Link>
            }) 
          }
        </div>
        <div className="text-secondary text-center mt-5 mb-5">
          <span style={{fontSize: "130%"}} className="wave mx-1">🏂</span> {` Developed by`} <Link href="https://www.linkedin.com/in/thisisadityapatel/" style={{textDecoration:"underline"}} className='text-secondary'>Aditya Patel</Link> {`© ${current_Date.getFullYear()} All Rights Reserved.`}
        </div>
      </div>
      <footer></footer>
    </>
  )
}
